export default {
    GEORISKS_SET_STATE: 'GeoRisks/GEORISKS_SET_STATE',
    GEORISKS_ACTION_GET: 'GeoRisks/GEORISKS_ACTION_GET',

    CSP_SET_STATE: 'CSP/CSP_SET_STATE',
    CSP_ACTION_GET: 'CSP/CSP_ACTION_GET',
}